spring:
  datasource:
    url: jdbc:mysql://localhost:3306/librarysystem?allowPublicKeyRetrieval=false&useSSL=false
    username: root
    password: 839251Ab


    #JPA setting
  jpa.hibernate.ddl_auto: update



  #spring.application.name=library-testproject

